##spring:
##  jpa:
##    show-sql: true
##    hibernate:
##      ddl-auto: create-drop
##
##  datasource:
##    url: jdbc:mysql://localhost:3306/movieDB
##    username: root
##    password: 12345
##    driverClassName: com.mysql.jdbc.Driver
##
##  server:
##    port: 8090
#spring:
#  mongodb:
#      datasource:
#        url : jdbc:mongo://localhost:27017/movieDB
#        username: root
#        password: 12345
#        driverClassName : com.mongodb.jdbc.MongoDriver
#
